sudo: false
language: ruby
rvm:
  - 2.5.5
  - 2.6.2
  - ruby-head
branches:
  only:
    - master
cache: bundler
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - travis_retry bundle install
  - travis_retry bundle update
  - gem build indonesian-territory-rails.gemspec
  - gem install ./indonesian-territory-rails-*.gem
notifications:
  email: false
