Regency.create([
	{ province_id: 1, name: "KABUPATEN SIMEULUE" },
	{ province_id: 1, name: "KABUPATEN ACEH SINGKIL" },
	{ province_id: 1, name: "KABUPATEN ACEH SELATAN" },
	{ province_id: 1, name: "KABUPATEN ACEH TENGGARA" },
	{ province_id: 1, name: "KABUPATEN ACEH TIMUR" },
	{ province_id: 1, name: "KABUPATEN ACEH TENGAH" },
	{ province_id: 1, name: "KABUPATEN ACEH BARAT" },
	{ province_id: 1, name: "KABUPATEN ACEH BESAR" },
	{ province_id: 1, name: "KABUPATEN PIDIE" },
	{ province_id: 1, name: "KABUPATEN BIREUEN" },
	{ province_id: 1, name: "KABUPATEN ACEH UTARA" },
	{ province_id: 1, name: "KABUPATEN ACEH BARAT DAYA" },
	{ province_id: 1, name: "KABUPATEN GAYO LUES" },
	{ province_id: 1, name: "KABUPATEN ACEH TAMIANG" },
	{ province_id: 1, name: "KABUPATEN NAGAN RAYA" },
	{ province_id: 1, name: "KABUPATEN ACEH JAYA" },
	{ province_id: 1, name: "KABUPATEN BENER MERIAH" },
	{ province_id: 1, name: "KABUPATEN PIDIE JAYA" },
	{ province_id: 1, name: "KOTA BANDA ACEH" },
	{ province_id: 1, name: "KOTA SABANG" },
	{ province_id: 1, name: "KOTA LANGSA" },
	{ province_id: 1, name: "KOTA LHOKSEUMAWE" },
	{ province_id: 1, name: "KOTA SUBULUSSALAM" },
	{ province_id: 2, name: "KABUPATEN NIAS" },
	{ province_id: 2, name: "KABUPATEN MANDAILING NATAL" },
	{ province_id: 2, name: "KABUPATEN TAPANULI SELATAN" },
	{ province_id: 2, name: "KABUPATEN TAPANULI TENGAH" },
	{ province_id: 2, name: "KABUPATEN TAPANULI UTARA" },
	{ province_id: 2, name: "KABUPATEN TOBA SAMOSIR" },
	{ province_id: 2, name: "KABUPATEN LABUHAN BATU" },
	{ province_id: 2, name: "KABUPATEN ASAHAN" },
	{ province_id: 2, name: "KABUPATEN SIMALUNGUN" },
	{ province_id: 2, name: "KABUPATEN DAIRI" },
	{ province_id: 2, name: "KABUPATEN KARO" },
	{ province_id: 2, name: "KABUPATEN DELI SERDANG" },
	{ province_id: 2, name: "KABUPATEN LANGKAT" },
	{ province_id: 2, name: "KABUPATEN NIAS SELATAN" },
	{ province_id: 2, name: "KABUPATEN HUMBANG HASUNDUTAN" },
	{ province_id: 2, name: "KABUPATEN PAKPAK BHARAT" },
	{ province_id: 2, name: "KABUPATEN SAMOSIR" },
	{ province_id: 2, name: "KABUPATEN SERDANG BEDAGAI" },
	{ province_id: 2, name: "KABUPATEN BATU BARA" },
	{ province_id: 2, name: "KABUPATEN PADANG LAWAS UTARA" },
	{ province_id: 2, name: "KABUPATEN PADANG LAWAS" },
	{ province_id: 2, name: "KABUPATEN LABUHAN BATU SELATAN" },
	{ province_id: 2, name: "KABUPATEN LABUHAN BATU UTARA" },
	{ province_id: 2, name: "KABUPATEN NIAS UTARA" },
	{ province_id: 2, name: "KABUPATEN NIAS BARAT" },
	{ province_id: 2, name: "KOTA SIBOLGA" },
	{ province_id: 2, name: "KOTA TANJUNG BALAI" },
	{ province_id: 2, name: "KOTA PEMATANG SIANTAR" },
	{ province_id: 2, name: "KOTA TEBING TINGGI" },
	{ province_id: 2, name: "KOTA MEDAN" },
	{ province_id: 2, name: "KOTA BINJAI" },
	{ province_id: 2, name: "KOTA PADANGSIDIMPUAN" },
	{ province_id: 2, name: "KOTA GUNUNGSITOLI" },
	{ province_id: 3, name: "KABUPATEN KEPULAUAN MENTAWAI" },
	{ province_id: 3, name: "KABUPATEN PESISIR SELATAN" },
	{ province_id: 3, name: "KABUPATEN SOLOK" },
	{ province_id: 3, name: "KABUPATEN SIJUNJUNG" },
	{ province_id: 3, name: "KABUPATEN TANAH DATAR" },
	{ province_id: 3, name: "KABUPATEN PADANG PARIAMAN" },
	{ province_id: 3, name: "KABUPATEN AGAM" },
	{ province_id: 3, name: "KABUPATEN LIMA PULUH KOTA" },
	{ province_id: 3, name: "KABUPATEN PASAMAN" },
	{ province_id: 3, name: "KABUPATEN SOLOK SELATAN" },
	{ province_id: 3, name: "KABUPATEN DHARMASRAYA" },
	{ province_id: 3, name: "KABUPATEN PASAMAN BARAT" },
	{ province_id: 3, name: "KOTA PADANG" },
	{ province_id: 3, name: "KOTA SOLOK" },
	{ province_id: 3, name: "KOTA SAWAH LUNTO" },
	{ province_id: 3, name: "KOTA PADANG PANJANG" },
	{ province_id: 3, name: "KOTA BUKITTINGGI" },
	{ province_id: 3, name: "KOTA PAYAKUMBUH" },
	{ province_id: 3, name: "KOTA PARIAMAN" },
	{ province_id: 4, name: "KABUPATEN KUANTAN SINGINGI" },
	{ province_id: 4, name: "KABUPATEN INDRAGIRI HULU" },
	{ province_id: 4, name: "KABUPATEN INDRAGIRI HILIR" },
	{ province_id: 4, name: "KABUPATEN PELALAWAN" },
	{ province_id: 4, name: "KABUPATEN SIAK" },
	{ province_id: 4, name: "KABUPATEN KAMPAR" },
	{ province_id: 4, name: "KABUPATEN ROKAN HULU" },
	{ province_id: 4, name: "KABUPATEN BENGKALIS" },
	{ province_id: 4, name: "KABUPATEN ROKAN HILIR" },
	{ province_id: 4, name: "KABUPATEN KEPULAUAN MERANTI" },
	{ province_id: 4, name: "KOTA PEKANBARU" },
	{ province_id: 4, name: "KOTA DUMAI" },
	{ province_id: 5, name: "KABUPATEN KERINCI" },
	{ province_id: 5, name: "KABUPATEN MERANGIN" },
	{ province_id: 5, name: "KABUPATEN SAROLANGUN" },
	{ province_id: 5, name: "KABUPATEN BATANG HARI" },
	{ province_id: 5, name: "KABUPATEN MUARO JAMBI" },
	{ province_id: 5, name: "KABUPATEN TANJUNG JABUNG TIMUR" },
	{ province_id: 5, name: "KABUPATEN TANJUNG JABUNG BARAT" },
	{ province_id: 5, name: "KABUPATEN TEBO" },
	{ province_id: 5, name: "KABUPATEN BUNGO" },
	{ province_id: 5, name: "KOTA JAMBI" },
	{ province_id: 5, name: "KOTA SUNGAI PENUH" },
	{ province_id: 6, name: "KABUPATEN OGAN KOMERING ULU" },
	{ province_id: 6, name: "KABUPATEN OGAN KOMERING ILIR" },
	{ province_id: 6, name: "KABUPATEN MUARA ENIM" },
	{ province_id: 6, name: "KABUPATEN LAHAT" },
	{ province_id: 6, name: "KABUPATEN MUSI RAWAS" },
	{ province_id: 6, name: "KABUPATEN MUSI BANYUASIN" },
	{ province_id: 6, name: "KABUPATEN BANYU ASIN" },
	{ province_id: 6, name: "KABUPATEN OGAN KOMERING ULU SELATAN" },
	{ province_id: 6, name: "KABUPATEN OGAN KOMERING ULU TIMUR" },
	{ province_id: 6, name: "KABUPATEN OGAN ILIR" },
	{ province_id: 6, name: "KABUPATEN EMPAT LAWANG" },
	{ province_id: 6, name: "KABUPATEN PENUKAL ABAB LEMATANG ILIR" },
	{ province_id: 6, name: "KABUPATEN MUSI RAWAS UTARA" },
	{ province_id: 6, name: "KOTA PALEMBANG" },
	{ province_id: 6, name: "KOTA PRABUMULIH" },
	{ province_id: 6, name: "KOTA PAGAR ALAM" },
	{ province_id: 6, name: "KOTA LUBUKLINGGAU" },
	{ province_id: 7, name: "KABUPATEN BENGKULU SELATAN" },
	{ province_id: 7, name: "KABUPATEN REJANG LEBONG" },
	{ province_id: 7, name: "KABUPATEN BENGKULU UTARA" },
	{ province_id: 7, name: "KABUPATEN KAUR" },
	{ province_id: 7, name: "KABUPATEN SELUMA" },
	{ province_id: 7, name: "KABUPATEN MUKOMUKO" },
	{ province_id: 7, name: "KABUPATEN LEBONG" },
	{ province_id: 7, name: "KABUPATEN KEPAHIANG" },
	{ province_id: 7, name: "KABUPATEN BENGKULU TENGAH" },
	{ province_id: 7, name: "KOTA BENGKULU" },
	{ province_id: 8, name: "KABUPATEN LAMPUNG BARAT" },
	{ province_id: 8, name: "KABUPATEN TANGGAMUS" },
	{ province_id: 8, name: "KABUPATEN LAMPUNG SELATAN" },
	{ province_id: 8, name: "KABUPATEN LAMPUNG TIMUR" },
	{ province_id: 8, name: "KABUPATEN LAMPUNG TENGAH" },
	{ province_id: 8, name: "KABUPATEN LAMPUNG UTARA" },
	{ province_id: 8, name: "KABUPATEN WAY KANAN" },
	{ province_id: 8, name: "KABUPATEN TULANGBAWANG" },
	{ province_id: 8, name: "KABUPATEN PESAWARAN" },
	{ province_id: 8, name: "KABUPATEN PRINGSEWU" },
	{ province_id: 8, name: "KABUPATEN MESUJI" },
	{ province_id: 8, name: "KABUPATEN TULANG BAWANG BARAT" },
	{ province_id: 8, name: "KABUPATEN PESISIR BARAT" },
	{ province_id: 8, name: "KOTA BANDAR LAMPUNG" },
	{ province_id: 8, name: "KOTA METRO" },
	{ province_id: 9, name: "KABUPATEN BANGKA" },
	{ province_id: 9, name: "KABUPATEN BELITUNG" },
	{ province_id: 9, name: "KABUPATEN BANGKA BARAT" },
	{ province_id: 9, name: "KABUPATEN BANGKA TENGAH" },
	{ province_id: 9, name: "KABUPATEN BANGKA SELATAN" },
	{ province_id: 9, name: "KABUPATEN BELITUNG TIMUR" },
	{ province_id: 9, name: "KOTA PANGKAL PINANG" },
	{ province_id: 10, name: "KABUPATEN KARIMUN" },
	{ province_id: 10, name: "KABUPATEN BINTAN" },
	{ province_id: 10, name: "KABUPATEN NATUNA" },
	{ province_id: 10, name: "KABUPATEN LINGGA" },
	{ province_id: 10, name: "KABUPATEN KEPULAUAN ANAMBAS" },
	{ province_id: 10, name: "KOTA BATAM" },
	{ province_id: 10, name: "KOTA TANJUNG PINANG" },
	{ province_id: 11, name: "KABUPATEN KEPULAUAN SERIBU" },
	{ province_id: 11, name: "KOTA JAKARTA SELATAN" },
	{ province_id: 11, name: "KOTA JAKARTA TIMUR" },
	{ province_id: 11, name: "KOTA JAKARTA PUSAT" },
	{ province_id: 11, name: "KOTA JAKARTA BARAT" },
	{ province_id: 11, name: "KOTA JAKARTA UTARA" },
	{ province_id: 12, name: "KABUPATEN BOGOR" },
	{ province_id: 12, name: "KABUPATEN SUKABUMI" },
	{ province_id: 12, name: "KABUPATEN CIANJUR" },
	{ province_id: 12, name: "KABUPATEN BANDUNG" },
	{ province_id: 12, name: "KABUPATEN GARUT" },
	{ province_id: 12, name: "KABUPATEN TASIKMALAYA" },
	{ province_id: 12, name: "KABUPATEN CIAMIS" },
	{ province_id: 12, name: "KABUPATEN KUNINGAN" },
	{ province_id: 12, name: "KABUPATEN CIREBON" },
	{ province_id: 12, name: "KABUPATEN MAJALENGKA" },
	{ province_id: 12, name: "KABUPATEN SUMEDANG" },
	{ province_id: 12, name: "KABUPATEN INDRAMAYU" },
	{ province_id: 12, name: "KABUPATEN SUBANG" },
	{ province_id: 12, name: "KABUPATEN PURWAKARTA" },
	{ province_id: 12, name: "KABUPATEN KARAWANG" },
	{ province_id: 12, name: "KABUPATEN BEKASI" },
	{ province_id: 12, name: "KABUPATEN BANDUNG BARAT" },
	{ province_id: 12, name: "KABUPATEN PANGANDARAN" },
	{ province_id: 12, name: "KOTA BOGOR" },
	{ province_id: 12, name: "KOTA SUKABUMI" },
	{ province_id: 12, name: "KOTA BANDUNG" },
	{ province_id: 12, name: "KOTA CIREBON" },
	{ province_id: 12, name: "KOTA BEKASI" },
	{ province_id: 12, name: "KOTA DEPOK" },
	{ province_id: 12, name: "KOTA CIMAHI" },
	{ province_id: 12, name: "KOTA TASIKMALAYA" },
	{ province_id: 12, name: "KOTA BANJAR" },
	{ province_id: 13, name: "KABUPATEN CILACAP" },
	{ province_id: 13, name: "KABUPATEN BANYUMAS" },
	{ province_id: 13, name: "KABUPATEN PURBALINGGA" },
	{ province_id: 13, name: "KABUPATEN BANJARNEGARA" },
	{ province_id: 13, name: "KABUPATEN KEBUMEN" },
	{ province_id: 13, name: "KABUPATEN PURWOREJO" },
	{ province_id: 13, name: "KABUPATEN WONOSOBO" },
	{ province_id: 13, name: "KABUPATEN MAGELANG" },
	{ province_id: 13, name: "KABUPATEN BOYOLALI" },
	{ province_id: 13, name: "KABUPATEN KLATEN" },
	{ province_id: 13, name: "KABUPATEN SUKOHARJO" },
	{ province_id: 13, name: "KABUPATEN WONOGIRI" },
	{ province_id: 13, name: "KABUPATEN KARANGANYAR" },
	{ province_id: 13, name: "KABUPATEN SRAGEN" },
	{ province_id: 13, name: "KABUPATEN GROBOGAN" },
	{ province_id: 13, name: "KABUPATEN BLORA" },
	{ province_id: 13, name: "KABUPATEN REMBANG" },
	{ province_id: 13, name: "KABUPATEN PATI" },
	{ province_id: 13, name: "KABUPATEN KUDUS" },
	{ province_id: 13, name: "KABUPATEN JEPARA" },
	{ province_id: 13, name: "KABUPATEN DEMAK" },
	{ province_id: 13, name: "KABUPATEN SEMARANG" },
	{ province_id: 13, name: "KABUPATEN TEMANGGUNG" },
	{ province_id: 13, name: "KABUPATEN KENDAL" },
	{ province_id: 13, name: "KABUPATEN BATANG" },
	{ province_id: 13, name: "KABUPATEN PEKALONGAN" },
	{ province_id: 13, name: "KABUPATEN PEMALANG" },
	{ province_id: 13, name: "KABUPATEN TEGAL" },
	{ province_id: 13, name: "KABUPATEN BREBES" },
	{ province_id: 13, name: "KOTA MAGELANG" },
	{ province_id: 13, name: "KOTA SURAKARTA" },
	{ province_id: 13, name: "KOTA SALATIGA" },
	{ province_id: 13, name: "KOTA SEMARANG" },
	{ province_id: 13, name: "KOTA PEKALONGAN" },
	{ province_id: 13, name: "KOTA TEGAL" },
	{ province_id: 14, name: "KABUPATEN KULON PROGO" },
	{ province_id: 14, name: "KABUPATEN BANTUL" },
	{ province_id: 14, name: "KABUPATEN GUNUNG KIDUL" },
	{ province_id: 14, name: "KABUPATEN SLEMAN" },
	{ province_id: 14, name: "KOTA YOGYAKARTA" },
	{ province_id: 15, name: "KABUPATEN PACITAN" },
	{ province_id: 15, name: "KABUPATEN PONOROGO" },
	{ province_id: 15, name: "KABUPATEN TRENGGALEK" },
	{ province_id: 15, name: "KABUPATEN TULUNGAGUNG" },
	{ province_id: 15, name: "KABUPATEN BLITAR" },
	{ province_id: 15, name: "KABUPATEN KEDIRI" },
	{ province_id: 15, name: "KABUPATEN MALANG" },
	{ province_id: 15, name: "KABUPATEN LUMAJANG" },
	{ province_id: 15, name: "KABUPATEN JEMBER" },
	{ province_id: 15, name: "KABUPATEN BANYUWANGI" },
	{ province_id: 15, name: "KABUPATEN BONDOWOSO" },
	{ province_id: 15, name: "KABUPATEN SITUBONDO" },
	{ province_id: 15, name: "KABUPATEN PROBOLINGGO" },
	{ province_id: 15, name: "KABUPATEN PASURUAN" },
	{ province_id: 15, name: "KABUPATEN SIDOARJO" },
	{ province_id: 15, name: "KABUPATEN MOJOKERTO" },
	{ province_id: 15, name: "KABUPATEN JOMBANG" },
	{ province_id: 15, name: "KABUPATEN NGANJUK" },
	{ province_id: 15, name: "KABUPATEN MADIUN" },
	{ province_id: 15, name: "KABUPATEN MAGETAN" },
	{ province_id: 15, name: "KABUPATEN NGAWI" },
	{ province_id: 15, name: "KABUPATEN BOJONEGORO" },
	{ province_id: 15, name: "KABUPATEN TUBAN" },
	{ province_id: 15, name: "KABUPATEN LAMONGAN" },
	{ province_id: 15, name: "KABUPATEN GRESIK" },
	{ province_id: 15, name: "KABUPATEN BANGKALAN" },
	{ province_id: 15, name: "KABUPATEN SAMPANG" },
	{ province_id: 15, name: "KABUPATEN PAMEKASAN" },
	{ province_id: 15, name: "KABUPATEN SUMENEP" },
	{ province_id: 15, name: "KOTA KEDIRI" },
	{ province_id: 15, name: "KOTA BLITAR" },
	{ province_id: 15, name: "KOTA MALANG" },
	{ province_id: 15, name: "KOTA PROBOLINGGO" },
	{ province_id: 15, name: "KOTA PASURUAN" },
	{ province_id: 15, name: "KOTA MOJOKERTO" },
	{ province_id: 15, name: "KOTA MADIUN" },
	{ province_id: 15, name: "KOTA SURABAYA" },
	{ province_id: 15, name: "KOTA BATU" },
	{ province_id: 16, name: "KABUPATEN PANDEGLANG" },
	{ province_id: 16, name: "KABUPATEN LEBAK" },
	{ province_id: 16, name: "KABUPATEN TANGERANG" },
	{ province_id: 16, name: "KABUPATEN SERANG" },
	{ province_id: 16, name: "KOTA TANGERANG" },
	{ province_id: 16, name: "KOTA CILEGON" },
	{ province_id: 16, name: "KOTA SERANG" },
	{ province_id: 16, name: "KOTA TANGERANG SELATAN" },
	{ province_id: 17, name: "KABUPATEN JEMBRANA" },
	{ province_id: 17, name: "KABUPATEN TABANAN" },
	{ province_id: 17, name: "KABUPATEN BADUNG" },
	{ province_id: 17, name: "KABUPATEN GIANYAR" },
	{ province_id: 17, name: "KABUPATEN KLUNGKUNG" },
	{ province_id: 17, name: "KABUPATEN BANGLI" },
	{ province_id: 17, name: "KABUPATEN KARANG ASEM" },
	{ province_id: 17, name: "KABUPATEN BULELENG" },
	{ province_id: 17, name: "KOTA DENPASAR" },
	{ province_id: 18, name: "KABUPATEN LOMBOK BARAT" },
	{ province_id: 18, name: "KABUPATEN LOMBOK TENGAH" },
	{ province_id: 18, name: "KABUPATEN LOMBOK TIMUR" },
	{ province_id: 18, name: "KABUPATEN SUMBAWA" },
	{ province_id: 18, name: "KABUPATEN DOMPU" },
	{ province_id: 18, name: "KABUPATEN BIMA" },
	{ province_id: 18, name: "KABUPATEN SUMBAWA BARAT" },
	{ province_id: 18, name: "KABUPATEN LOMBOK UTARA" },
	{ province_id: 18, name: "KOTA MATARAM" },
	{ province_id: 18, name: "KOTA BIMA" },
	{ province_id: 19, name: "KABUPATEN SUMBA BARAT" },
	{ province_id: 19, name: "KABUPATEN SUMBA TIMUR" },
	{ province_id: 19, name: "KABUPATEN KUPANG" },
	{ province_id: 19, name: "KABUPATEN TIMOR TENGAH SELATAN" },
	{ province_id: 19, name: "KABUPATEN TIMOR TENGAH UTARA" },
	{ province_id: 19, name: "KABUPATEN BELU" },
	{ province_id: 19, name: "KABUPATEN ALOR" },
	{ province_id: 19, name: "KABUPATEN LEMBATA" },
	{ province_id: 19, name: "KABUPATEN FLORES TIMUR" },
	{ province_id: 19, name: "KABUPATEN SIKKA" },
	{ province_id: 19, name: "KABUPATEN ENDE" },
	{ province_id: 19, name: "KABUPATEN NGADA" },
	{ province_id: 19, name: "KABUPATEN MANGGARAI" },
	{ province_id: 19, name: "KABUPATEN ROTE NDAO" },
	{ province_id: 19, name: "KABUPATEN MANGGARAI BARAT" },
	{ province_id: 19, name: "KABUPATEN SUMBA TENGAH" },
	{ province_id: 19, name: "KABUPATEN SUMBA BARAT DAYA" },
	{ province_id: 19, name: "KABUPATEN NAGEKEO" },
	{ province_id: 19, name: "KABUPATEN MANGGARAI TIMUR" },
	{ province_id: 19, name: "KABUPATEN SABU RAIJUA" },
	{ province_id: 19, name: "KABUPATEN MALAKA" },
	{ province_id: 19, name: "KOTA KUPANG" },
	{ province_id: 20, name: "KABUPATEN SAMBAS" },
	{ province_id: 20, name: "KABUPATEN BENGKAYANG" },
	{ province_id: 20, name: "KABUPATEN LANDAK" },
	{ province_id: 20, name: "KABUPATEN MEMPAWAH" },
	{ province_id: 20, name: "KABUPATEN SANGGAU" },
	{ province_id: 20, name: "KABUPATEN KETAPANG" },
	{ province_id: 20, name: "KABUPATEN SINTANG" },
	{ province_id: 20, name: "KABUPATEN KAPUAS HULU" },
	{ province_id: 20, name: "KABUPATEN SEKADAU" },
	{ province_id: 20, name: "KABUPATEN MELAWI" },
	{ province_id: 20, name: "KABUPATEN KAYONG UTARA" },
	{ province_id: 20, name: "KABUPATEN KUBU RAYA" },
	{ province_id: 20, name: "KOTA PONTIANAK" },
	{ province_id: 20, name: "KOTA SINGKAWANG" },
	{ province_id: 21, name: "KABUPATEN KOTAWARINGIN BARAT" },
	{ province_id: 21, name: "KABUPATEN KOTAWARINGIN TIMUR" },
	{ province_id: 21, name: "KABUPATEN KAPUAS" },
	{ province_id: 21, name: "KABUPATEN BARITO SELATAN" },
	{ province_id: 21, name: "KABUPATEN BARITO UTARA" },
	{ province_id: 21, name: "KABUPATEN SUKAMARA" },
	{ province_id: 21, name: "KABUPATEN LAMANDAU" },
	{ province_id: 21, name: "KABUPATEN SERUYAN" },
	{ province_id: 21, name: "KABUPATEN KATINGAN" },
	{ province_id: 21, name: "KABUPATEN PULANG PISAU" },
	{ province_id: 21, name: "KABUPATEN GUNUNG MAS" },
	{ province_id: 21, name: "KABUPATEN BARITO TIMUR" },
	{ province_id: 21, name: "KABUPATEN MURUNG RAYA" },
	{ province_id: 21, name: "KOTA PALANGKA RAYA" },
	{ province_id: 22, name: "KABUPATEN TANAH LAUT" },
	{ province_id: 22, name: "KABUPATEN KOTA BARU" },
	{ province_id: 22, name: "KABUPATEN BANJAR" },
	{ province_id: 22, name: "KABUPATEN BARITO KUALA" },
	{ province_id: 22, name: "KABUPATEN TAPIN" },
	{ province_id: 22, name: "KABUPATEN HULU SUNGAI SELATAN" },
	{ province_id: 22, name: "KABUPATEN HULU SUNGAI TENGAH" },
	{ province_id: 22, name: "KABUPATEN HULU SUNGAI UTARA" },
	{ province_id: 22, name: "KABUPATEN TABALONG" },
	{ province_id: 22, name: "KABUPATEN TANAH BUMBU" },
	{ province_id: 22, name: "KABUPATEN BALANGAN" },
	{ province_id: 22, name: "KOTA BANJARMASIN" },
	{ province_id: 22, name: "KOTA BANJAR BARU" },
	{ province_id: 23, name: "KABUPATEN PASER" },
	{ province_id: 23, name: "KABUPATEN KUTAI BARAT" },
	{ province_id: 23, name: "KABUPATEN KUTAI KARTANEGARA" },
	{ province_id: 23, name: "KABUPATEN KUTAI TIMUR" },
	{ province_id: 23, name: "KABUPATEN BERAU" },
	{ province_id: 23, name: "KABUPATEN PENAJAM PASER UTARA" },
	{ province_id: 23, name: "KABUPATEN MAHAKAM HULU" },
	{ province_id: 23, name: "KOTA BALIKPAPAN" },
	{ province_id: 23, name: "KOTA SAMARINDA" },
	{ province_id: 23, name: "KOTA BONTANG" },
	{ province_id: 24, name: "KABUPATEN MALINAU" },
	{ province_id: 24, name: "KABUPATEN BULUNGAN" },
	{ province_id: 24, name: "KABUPATEN TANA TIDUNG" },
	{ province_id: 24, name: "KABUPATEN NUNUKAN" },
	{ province_id: 24, name: "KOTA TARAKAN" },
	{ province_id: 25, name: "KABUPATEN BOLAANG MONGONDOW" },
	{ province_id: 25, name: "KABUPATEN MINAHASA" },
	{ province_id: 25, name: "KABUPATEN KEPULAUAN SANGIHE" },
	{ province_id: 25, name: "KABUPATEN KEPULAUAN TALAUD" },
	{ province_id: 25, name: "KABUPATEN MINAHASA SELATAN" },
	{ province_id: 25, name: "KABUPATEN MINAHASA UTARA" },
	{ province_id: 25, name: "KABUPATEN BOLAANG MONGONDOW UTARA" },
	{ province_id: 25, name: "KABUPATEN SIAU TAGULANDANG BIARO" },
	{ province_id: 25, name: "KABUPATEN MINAHASA TENGGARA" },
	{ province_id: 25, name: "KABUPATEN BOLAANG MONGONDOW SELATAN" },
	{ province_id: 25, name: "KABUPATEN BOLAANG MONGONDOW TIMUR" },
	{ province_id: 25, name: "KOTA MANADO" },
	{ province_id: 25, name: "KOTA BITUNG" },
	{ province_id: 25, name: "KOTA TOMOHON" },
	{ province_id: 25, name: "KOTA KOTAMOBAGU" },
	{ province_id: 26, name: "KABUPATEN BANGGAI KEPULAUAN" },
	{ province_id: 26, name: "KABUPATEN BANGGAI" },
	{ province_id: 26, name: "KABUPATEN MOROWALI" },
	{ province_id: 26, name: "KABUPATEN POSO" },
	{ province_id: 26, name: "KABUPATEN DONGGALA" },
	{ province_id: 26, name: "KABUPATEN TOLI-TOLI" },
	{ province_id: 26, name: "KABUPATEN BUOL" },
	{ province_id: 26, name: "KABUPATEN PARIGI MOUTONG" },
	{ province_id: 26, name: "KABUPATEN TOJO UNA-UNA" },
	{ province_id: 26, name: "KABUPATEN SIGI" },
	{ province_id: 26, name: "KABUPATEN BANGGAI LAUT" },
	{ province_id: 26, name: "KABUPATEN MOROWALI UTARA" },
	{ province_id: 26, name: "KOTA PALU" },
	{ province_id: 27, name: "KABUPATEN KEPULAUAN SELAYAR" },
	{ province_id: 27, name: "KABUPATEN BULUKUMBA" },
	{ province_id: 27, name: "KABUPATEN BANTAENG" },
	{ province_id: 27, name: "KABUPATEN JENEPONTO" },
	{ province_id: 27, name: "KABUPATEN TAKALAR" },
	{ province_id: 27, name: "KABUPATEN GOWA" },
	{ province_id: 27, name: "KABUPATEN SINJAI" },
	{ province_id: 27, name: "KABUPATEN MAROS" },
	{ province_id: 27, name: "KABUPATEN PANGKAJENE DAN KEPULAUAN" },
	{ province_id: 27, name: "KABUPATEN BARRU" },
	{ province_id: 27, name: "KABUPATEN BONE" },
	{ province_id: 27, name: "KABUPATEN SOPPENG" },
	{ province_id: 27, name: "KABUPATEN WAJO" },
	{ province_id: 27, name: "KABUPATEN SIDENRENG RAPPANG" },
	{ province_id: 27, name: "KABUPATEN PINRANG" },
	{ province_id: 27, name: "KABUPATEN ENREKANG" },
	{ province_id: 27, name: "KABUPATEN LUWU" },
	{ province_id: 27, name: "KABUPATEN TANA TORAJA" },
	{ province_id: 27, name: "KABUPATEN LUWU UTARA" },
	{ province_id: 27, name: "KABUPATEN LUWU TIMUR" },
	{ province_id: 27, name: "KABUPATEN TORAJA UTARA" },
	{ province_id: 27, name: "KOTA MAKASSAR" },
	{ province_id: 27, name: "KOTA PAREPARE" },
	{ province_id: 27, name: "KOTA PALOPO" },
	{ province_id: 28, name: "KABUPATEN BUTON" },
	{ province_id: 28, name: "KABUPATEN MUNA" },
	{ province_id: 28, name: "KABUPATEN KONAWE" },
	{ province_id: 28, name: "KABUPATEN KOLAKA" },
	{ province_id: 28, name: "KABUPATEN KONAWE SELATAN" },
	{ province_id: 28, name: "KABUPATEN BOMBANA" },
	{ province_id: 28, name: "KABUPATEN WAKATOBI" },
	{ province_id: 28, name: "KABUPATEN KOLAKA UTARA" },
	{ province_id: 28, name: "KABUPATEN BUTON UTARA" },
	{ province_id: 28, name: "KABUPATEN KONAWE UTARA" },
	{ province_id: 28, name: "KABUPATEN KOLAKA TIMUR" },
	{ province_id: 28, name: "KABUPATEN KONAWE KEPULAUAN" },
	{ province_id: 28, name: "KABUPATEN MUNA BARAT" },
	{ province_id: 28, name: "KABUPATEN BUTON TENGAH" },
	{ province_id: 28, name: "KABUPATEN BUTON SELATAN" },
	{ province_id: 28, name: "KOTA KENDARI" },
	{ province_id: 28, name: "KOTA BAUBAU" },
	{ province_id: 29, name: "KABUPATEN BOALEMO" },
	{ province_id: 29, name: "KABUPATEN GORONTALO" },
	{ province_id: 29, name: "KABUPATEN POHUWATO" },
	{ province_id: 29, name: "KABUPATEN BONE BOLANGO" },
	{ province_id: 29, name: "KABUPATEN GORONTALO UTARA" },
	{ province_id: 29, name: "KOTA GORONTALO" },
	{ province_id: 30, name: "KABUPATEN MAJENE" },
	{ province_id: 30, name: "KABUPATEN POLEWALI MANDAR" },
	{ province_id: 30, name: "KABUPATEN MAMASA" },
	{ province_id: 30, name: "KABUPATEN MAMUJU" },
	{ province_id: 30, name: "KABUPATEN MAMUJU UTARA" },
	{ province_id: 30, name: "KABUPATEN MAMUJU TENGAH" },
	{ province_id: 31, name: "KABUPATEN MALUKU TENGGARA BARAT" },
	{ province_id: 31, name: "KABUPATEN MALUKU TENGGARA" },
	{ province_id: 31, name: "KABUPATEN MALUKU TENGAH" },
	{ province_id: 31, name: "KABUPATEN BURU" },
	{ province_id: 31, name: "KABUPATEN KEPULAUAN ARU" },
	{ province_id: 31, name: "KABUPATEN SERAM BAGIAN BARAT" },
	{ province_id: 31, name: "KABUPATEN SERAM BAGIAN TIMUR" },
	{ province_id: 31, name: "KABUPATEN MALUKU BARAT DAYA" },
	{ province_id: 31, name: "KABUPATEN BURU SELATAN" },
	{ province_id: 31, name: "KOTA AMBON" },
	{ province_id: 31, name: "KOTA TUAL" },
	{ province_id: 32, name: "KABUPATEN HALMAHERA BARAT" },
	{ province_id: 32, name: "KABUPATEN HALMAHERA TENGAH" },
	{ province_id: 32, name: "KABUPATEN KEPULAUAN SULA" },
	{ province_id: 32, name: "KABUPATEN HALMAHERA SELATAN" },
	{ province_id: 32, name: "KABUPATEN HALMAHERA UTARA" },
	{ province_id: 32, name: "KABUPATEN HALMAHERA TIMUR" },
	{ province_id: 32, name: "KABUPATEN PULAU MOROTAI" },
	{ province_id: 32, name: "KABUPATEN PULAU TALIABU" },
	{ province_id: 32, name: "KOTA TERNATE" },
	{ province_id: 32, name: "KOTA TIDORE KEPULAUAN" },
	{ province_id: 33, name: "KABUPATEN FAKFAK" },
	{ province_id: 33, name: "KABUPATEN KAIMANA" },
	{ province_id: 33, name: "KABUPATEN TELUK WONDAMA" },
	{ province_id: 33, name: "KABUPATEN TELUK BINTUNI" },
	{ province_id: 33, name: "KABUPATEN MANOKWARI" },
	{ province_id: 33, name: "KABUPATEN SORONG SELATAN" },
	{ province_id: 33, name: "KABUPATEN SORONG" },
	{ province_id: 33, name: "KABUPATEN RAJA AMPAT" },
	{ province_id: 33, name: "KABUPATEN TAMBRAUW" },
	{ province_id: 33, name: "KABUPATEN MAYBRAT" },
	{ province_id: 33, name: "KABUPATEN MANOKWARI SELATAN" },
	{ province_id: 33, name: "KABUPATEN PEGUNUNGAN ARFAK" },
	{ province_id: 33, name: "KOTA SORONG" },
	{ province_id: 34, name: "KABUPATEN MERAUKE" },
	{ province_id: 34, name: "KABUPATEN JAYAWIJAYA" },
	{ province_id: 34, name: "KABUPATEN JAYAPURA" },
	{ province_id: 34, name: "KABUPATEN NABIRE" },
	{ province_id: 34, name: "KABUPATEN KEPULAUAN YAPEN" },
	{ province_id: 34, name: "KABUPATEN BIAK NUMFOR" },
	{ province_id: 34, name: "KABUPATEN PANIAI" },
	{ province_id: 34, name: "KABUPATEN PUNCAK JAYA" },
	{ province_id: 34, name: "KABUPATEN MIMIKA" },
	{ province_id: 34, name: "KABUPATEN BOVEN DIGOEL" },
	{ province_id: 34, name: "KABUPATEN MAPPI" },
	{ province_id: 34, name: "KABUPATEN ASMAT" },
	{ province_id: 34, name: "KABUPATEN YAHUKIMO" },
	{ province_id: 34, name: "KABUPATEN PEGUNUNGAN BINTANG" },
	{ province_id: 34, name: "KABUPATEN TOLIKARA" },
	{ province_id: 34, name: "KABUPATEN SARMI" },
	{ province_id: 34, name: "KABUPATEN KEEROM" },
	{ province_id: 34, name: "KABUPATEN WAROPEN" },
	{ province_id: 34, name: "KABUPATEN SUPIORI" },
	{ province_id: 34, name: "KABUPATEN MAMBERAMO RAYA" },
	{ province_id: 34, name: "KABUPATEN NDUGA" },
	{ province_id: 34, name: "KABUPATEN LANNY JAYA" },
	{ province_id: 34, name: "KABUPATEN MAMBERAMO TENGAH" },
	{ province_id: 34, name: "KABUPATEN YALIMO" },
	{ province_id: 34, name: "KABUPATEN PUNCAK" },
	{ province_id: 34, name: "KABUPATEN DOGIYAI" },
	{ province_id: 34, name: "KABUPATEN INTAN JAYA" },
	{ province_id: 34, name: "KABUPATEN DEIYAI" },
	{ province_id: 34, name: "KOTA JAYAPURA" },
])
